# Generated by Django 5.0.6 on 2025-10-30 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyhuapi', '0002_booking_category_remove_cliente_usuario_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_clp',
        ),
        migrations.AddField(
            model_name='booking',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
