# Generated by Django 5.0.6 on 2025-10-30 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_image'),
        ('happyhuapi', '0003_remove_product_photo_remove_product_price_clp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='products',
            field=models.ManyToManyField(blank=True, to='catalog.product'),
        ),
    ]
