# Generated by Django 5.0.6 on 2025-11-26 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyhuapi', '0009_remove_product_category_delete_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('table_installed', models.BooleanField(default=False)),
                ('decoration_ready', models.BooleanField(default=False)),
                ('balloons_ready', models.BooleanField(default=False)),
                ('candy_ready', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='happyhuapi.booking')),
            ],
        ),
        migrations.CreateModel(
            name='EvidencePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='evidences/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='happyhuapi.evidence')),
            ],
        ),
    ]
