# Generated by Django 5.0.6 on 2025-10-31 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyhuapi', '0006_alter_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('done', 'Realizada'), ('cancelled', 'Cancelada')], default='pending', max_length=10, verbose_name='Estado'),
        ),
    ]
