# Generated by Django 5.0.6 on 2025-11-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyhuapi', '0010_booking_qr_image_evidence_evidencephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evidence',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
