# Generated by Django 5.0.6 on 2025-11-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyhuapi', '0011_evidence_completed_evidence_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evidencephoto',
            name='image',
            field=models.ImageField(upload_to='evidence_photos/'),
        ),
    ]
