# Generated by Django 5.2.6 on 2025-10-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut')),
                ('nombre', models.CharField(blank=True, max_length=50, verbose_name='Nombre')),
                ('usuario', models.CharField(blank=True, max_length=50, verbose_name='Usuario')),
                ('correo', models.EmailField(blank=True, max_length=50, verbose_name='Correo')),
                ('direccion', models.CharField(blank=True, max_length=50, verbose_name='Direccion')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='Telefono')),
            ],
        ),
    ]
